AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
